mongoHost: 127.0.0.1
mongoPort: 27017
mongoDatabase: testAutomationTooldb
swagger:
  resourcePackage: com.auxolabs.testAutomationTool
server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
